INSERT INTO genre( _id, name ) VALUES 
( 'ACTION', 'Action' ),
( 'ADVENTURE', 'Adventure' ),
( 'ARCADE', 'Arcade' ),
( 'BOARD', 'Board' ),
( 'CARD', 'Card' ),
( 'CASINO', 'Casino' ),
( 'CASUAL', 'Casual' ),
( 'EDUCATIONAL', 'Educational' ),
( 'MUSIC', 'Music' ),
( 'PUZZLE', 'Puzzle' ),
( 'RACING', 'Racing' ),
( 'ROLE_PLAYING', 'Role Playing' ),
( 'SIMULATION', 'Simulation' ),
( 'SPORTS', 'Sports' ),
( 'STRATEGY', 'Strategy' ),
( 'TRIVIA', 'Trivia' ),
( 'WORD', 'Word' );